version: "2.1"

networks:
  test:

services:
  api:
    image: api:1.0
    build: .
    networks:
      - test
    extra_hosts:
      - "peer0.org1.example.com:34.16.162.47"
      - "peer0.org2.example.com:34.125.181.46"
      - "peer0.org3.example.com:34.125.194.136"
      - "peer1.org1.example.com:34.16.162.47"
      - "peer1.org2.example.com:34.125.181.46"
      - "peer1.org3.example.com:34.125.194.136"
      - "orderer.example.com:34.125.34.4"
      - "orderer2.example.com:34.125.34.4"
      - "orderer3.example.com:34.125.34.4"
    ports:
      - 4000:4000
